spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/ecommerce_dev?authSource=admin
      auto-index-creation: true

logging:
  level:
    root: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
    com.example.ecommerce: DEBUG

server:
  port: 8080
